### ISSUE TITLE
默认情况下隐藏index.php apache重写规则

### ISSUE THREAD

**Issue by wang-tom** [kphcdr/ppphp#2]
apache 服务器默认情况下无正确隐藏index.php

 RewriteRule ^(.*)$ index.php?/$1 [QSA,PT,L]   //在RewriteRule 后面的index.php教程后面添加一个“?”

**Comment by kphcdr** [comment]
<IfModule mod_rewrite.c>
 RewriteEngine on
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteRule ^(.*)$ index.php/$1 [QSA,PT,L]
</IfModule>
