### ISSUE TITLE
post函数获取int值为0时，有bug

### ISSUE THREAD

**Issue by howgoo** [kphcdr/ppphp#4]
MyPPP\core\function\function.php

post 函数

$return = isset($_POST[$str])?$_POST[$str]:false;

如果此时，post的值为0时，if($return)会是true，会执行返回设置的默认值。

修正：如果$return是false时，再返回默认值。

![qq 20160926151819](https://cloud.githubusercontent.com/assets/283002/18825783/8327dbfc-83fc-11e6-9cbd-c54ed1093430.png)

**Comment by kphcdr** [comment]
感谢，已修复
